version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "✅ Hello from CircleCI Linux"
      - run: uname -a
      - run: sleep 30

workflows:
  build_and_test:
    jobs:
      - build
